// <auto-generated />
using System;
using DespensaBarrial.BD.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DespensaBarrial.BD.Migrations
{
    [DbContext(typeof(DespensaBarrialDbContext))]
    partial class DespensaBarrialDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DespensaBarrial.BD.Datos.Entidades.Administrador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreAdministador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NumeroTelefono")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int?>("proveedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("proveedorId");

                    b.ToTable("administrador");
                });

            modelBuilder.Entity("DespensaBarrial.BD.Datos.Entidades.Categorias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroDeCategoria")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductosId")
                        .HasColumnType("int");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<int?>("ProveedoresId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductosId");

                    b.HasIndex("ProveedoresId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("DespensaBarrial.BD.Datos.Entidades.Deposito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CategoriaProducto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmpleadoDepositoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("UnidadMinima")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoDepositoId");

                    b.ToTable("stockDeposito");
                });

            modelBuilder.Entity("DespensaBarrial.BD.Datos.Entidades.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Domicilio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EdadEmpleado")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreEmpleado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NumeroTelefono")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.ToTable("empleado");
                });

            modelBuilder.Entity("DespensaBarrial.BD.Datos.Entidades.Productos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaveProducto")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<int>("DepositoId")
                        .HasColumnType("int");

                    b.Property<string>("DescripcionProducto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimientoProducto")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioProducto")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepositoId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("DespensaBarrial.BD.Datos.Entidades.Proveedores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AdministadorId")
                        .HasColumnType("int");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DNI")
                        .HasMaxLength(8)
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("Date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroTelefono")
                        .HasMaxLength(8)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("DespensaBarrial.BD.Datos.Entidades.Administrador", b =>
                {
                    b.HasOne("DespensaBarrial.BD.Datos.Entidades.Proveedores", "proveedor")
                        .WithMany()
                        .HasForeignKey("proveedorId");

                    b.Navigation("proveedor");
                });

            modelBuilder.Entity("DespensaBarrial.BD.Datos.Entidades.Categorias", b =>
                {
                    b.HasOne("DespensaBarrial.BD.Datos.Entidades.Productos", "Productos")
                        .WithMany("categorias")
                        .HasForeignKey("ProductosId");

                    b.HasOne("DespensaBarrial.BD.Datos.Entidades.Proveedores", "Proveedores")
                        .WithMany("categorias")
                        .HasForeignKey("ProveedoresId");

                    b.Navigation("Productos");

                    b.Navigation("Proveedores");
                });

            modelBuilder.Entity("DespensaBarrial.BD.Datos.Entidades.Deposito", b =>
                {
                    b.HasOne("DespensaBarrial.BD.Datos.Entidades.Empleado", "EmpleadoDeposito")
                        .WithMany()
                        .HasForeignKey("EmpleadoDepositoId");

                    b.Navigation("EmpleadoDeposito");
                });

            modelBuilder.Entity("DespensaBarrial.BD.Datos.Entidades.Productos", b =>
                {
                    b.HasOne("DespensaBarrial.BD.Datos.Entidades.Deposito", null)
                        .WithMany("ProductosEnDeposito")
                        .HasForeignKey("DepositoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DespensaBarrial.BD.Datos.Entidades.Deposito", b =>
                {
                    b.Navigation("ProductosEnDeposito");
                });

            modelBuilder.Entity("DespensaBarrial.BD.Datos.Entidades.Productos", b =>
                {
                    b.Navigation("categorias");
                });

            modelBuilder.Entity("DespensaBarrial.BD.Datos.Entidades.Proveedores", b =>
                {
                    b.Navigation("categorias");
                });
#pragma warning restore 612, 618
        }
    }
}
